auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title



title: kailongli.github.io
url: http://kailongli.github.io
feed: /atom.xml
author_info: <a href="http://kailongli.github.io">kailongli</a>
